name: Build and push Docker images to Docker Hub

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - develop

jobs:
  build_docker_image:
    # This workflow is only of value to PyBaMM and would always be skipped in forks
    if: github.repository_owner == 'pybamm-team'
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker images
        run: |
          docker build -t pybamm:latest -f scripts/Dockerfile .

      - name: List built image(s)
        run: docker images
