name: Update version

on:
  workflow_dispatch:
    inputs:
      append_to_tag:
        description: 'Leave blank for an actual release or "rc1", "rc2", ..., for release candidates."'
        default: ""
  schedule:
     # Run at 10 am UTC on day-of-month 1 in January, May, and September.
     - cron: "0 10 1 1,5,9 *"

jobs:
  update-version:
    # This workflow is only of value to PyBaMM and would always be skipped in forks
    if: github.repository_owner == 'pybamm-team'
    runs-on: ubuntu-latest

    steps:
      - name: Get current date for the first release candidate
        if: github.event_name == 'schedule'
        run: |
          echo "VERSION=$(date +'v%y.%-m' + ".0")" >> $GITHUB_ENV

      - name: Get current date for a manual release
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "VERSION=$(date +'v%y.%-m')${{ github.event.inputs.append_to_tag }}" >> $GITHUB_ENV

      # the schedule workflow is for rc0 release
      - uses: actions/checkout@v4
        with:
          ref: 'develop'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -e ".[all]"

      # update all the version strings and add CHANGELOG headings
      - name: Update version
        run: python scripts/update_version.py

      # create a new version branch for rc0 release and commit
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Bump to ${{ env.VERSION }}'
          new_branch: '${{ env.VERSION }}'

      # checkout to develop for updating versions in the same
      - uses: actions/checkout@v4
        with:
          ref: 'develop'

      # update all the version strings
      - name: Update version
        run: python scripts/update_version.py

      # for final releases, create a PR from version branch to main
      - name: Make a PR from ${{ env.VERSION }} to main
        id: release_pr
        if: github.event_name == 'workflow_dispatch' && !startsWith(github.event.inputs.append_to_tag, 'rc')
        uses: repo-sync/pull-request@v2
        with:
          source_branch: '${{ env.VERSION }}'
          destination_branch: "main"
          pr_title: "Make release ${{ env.VERSION }}"
          pr_body: "**Check the [release workflow](https://github.com/pybamm-team/PyBaMM/blob/develop/.github/release_workflow.md)**"
          github_token: ${{ secrets.GITHUB_TOKEN }}
